version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go-commons"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/analytics"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/api-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/producer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/seeder"
    schedule:
      interval: "weekly"
