version: "2"
linters:
  default: none
  enable:
    - wsl_v5
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 70
      statements: 40
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
    cyclop:
      max-complexity: 15 
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
          - paralleltest
        path: integration-test
      - linters:
          - godot
        path: internal/controller/http
    paths:
      - bin/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/rauan06/realtime-map)
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - bin/
      - third_party$
      - builtin$
      - examples$