apiVersion: v1
kind: Service
metadata:
  name: map-analytics-service
spec:
  type: NodePort
  selector:
    app: map-analytics
  ports:
    - protocol: TCP
      port: 8080       # port inside the cluster
      targetPort: 8080 # container port
      nodePort: 30080  # port on your host
