name: Go Microservices CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [analytics, api-gateway, producer, seeder, go-commons, etl, dashboard, notification, anomaly]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'
          cache-dependency-path: ${{ matrix.service }}/go.sum

      - name: Test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: go test -v ./...

      - name: Run golangci-lint on ${{ matrix.service }}
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12.2
          working-directory: ${{ matrix.service }}
          args: --timeout=5m
