name: Go Microservices CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [analytics, api-gateway, producer, seeder, go-commons] # add more services if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'

      # - name: Build ${{ matrix.service }}
      #   working-directory: ${{ matrix.service }}
      #   run: go build -v ./...

      - name: Test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: go test -v ./...

      - name: Run golangci-lint on ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint run